IF
	See([PC])
	Delay(12)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
		ReallyForceSpell(Myself,WIZARD_DETECT_INVISIBILITY)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
		ReallyForceSpell([PC],WIZARD_DISPEL_MAGIC)
		ReallyForceSpell([PC],WIZARD_GREATER_MALISON)
		ReallyForceSpell([PC],WIZARD_HOLD_PERSON)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END


