IF
	See("F_DRIZZT")
	InParty("F_DRIZZT")
	Global("F_SpokeToDrizzt","LOCALS",0)
THEN
	RESPONSE #100
		Dialogue([PC])
END

IF
	AttackedBy([PC],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate([GOODCUTOFF],15)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),15)
END


